### PR TITLE
feat(uni-v3): add deploy uni-v3 contract and interface

### PR DESCRIPTION
**Pull request by DavidChild**
add deploy uni-v3 contract and interface.

### CODE REVIEW

**Comment by zhengjianhui** [comment]
Is this a copy of the source code? Why not use git clone and replace the configuration?

**Comment by DavidChild** [comment]
> Is this a copy of the source code? Why not use git clone and replace the configuration?

Because some source code will be modify, oK, I'll fork to my github, then adjust the way of release.

**Comment by zhengjianhui** [comment]
Why is the file suffix txt?
uni-v3-contract-deploy/code_files/createDeployContractStep.txt

**Comment by DavidChild** [comment]
> Why is the file suffix txt? uni-v3-contract-deploy/code_files/createDeployContractStep.txt @DavidChild

because this is just a replacement file, I can change the suffix to ts.

**Comment by 57u** [comment]
"constract" is a typo? Should say contract?

**Review by zhengjianhui — APPROVED** [review]

**Pull request merged**
